package com.antepod.lumentika.gesture

import com.antepod.lumentika.geometry.Point
import com.antepod.lumentika.platform.GestureConfiguration
import kotlin.math.hypot

public enum class GestureDisposition { PENDING, ACCEPTED, REJECTED }
public interface GestureRecognizer : AutoCloseable { public val team: Any?; public fun down(point:Point,timeNanos:Long); public fun move(point:Point,timeNanos:Long); public fun up(point:Point,timeNanos:Long); public fun cancel(); public fun resolve(disposition:GestureDisposition) }
public class GestureArena { private val entries=mutableMapOf<Int,MutableList<GestureRecognizer>>(); public fun add(pointer:Int,recognizer:GestureRecognizer){entries.getOrPut(pointer,::mutableListOf)+=recognizer}; public fun resolve(pointer:Int,winner:GestureRecognizer){entries.remove(pointer)?.forEach{it.resolve(if(it===winner||it.team!=null&&it.team===winner.team)GestureDisposition.ACCEPTED else GestureDisposition.REJECTED)}}; public fun cancel(pointer:Int){entries.remove(pointer)?.forEach{it.cancel()}} }
public class TapRecognizer(private val config:GestureConfiguration,private val onTap:()->Unit,override val team:Any?=null):GestureRecognizer { private var start=Point(0f,0f);private var rejected=false; override fun down(point:Point,timeNanos:Long){start=point;rejected=false};override fun move(point:Point,timeNanos:Long){if(hypot((point.x-start.x).toDouble(),(point.y-start.y).toDouble())>config.touchSlop)rejected=true};override fun up(point:Point,timeNanos:Long){if(!rejected)onTap()};override fun cancel(){rejected=true};override fun resolve(disposition:GestureDisposition){if(disposition==GestureDisposition.REJECTED)cancel()};override fun close()=cancel() }
public data class ScrollDelta(val x:Float,val y:Float){public operator fun minus(o:ScrollDelta)=ScrollDelta(x-o.x,y-o.y);public operator fun plus(o:ScrollDelta)=ScrollDelta(x+o.x,y+o.y)}
public enum class ScrollSource { WHEEL,DRAG,KEYBOARD,ACCESSIBILITY,PROGRAMMATIC,FLING }
public interface NestedScrollConnection { public fun preScroll(delta:ScrollDelta,source:ScrollSource)=ScrollDelta(0f,0f);public fun postScroll(consumed:ScrollDelta,remaining:ScrollDelta,source:ScrollSource)=ScrollDelta(0f,0f);public fun preFling(velocity:ScrollDelta)=ScrollDelta(0f,0f);public fun postFling(consumed:ScrollDelta,remaining:ScrollDelta)=ScrollDelta(0f,0f) }
public class ScrollState(initialX:Float=0f,initialY:Float=0f){public var x=initialX;private set;public var y=initialY;private set;public var maxX=0f;public var maxY=0f;public var overscroll=ScrollDelta(0f,0f);private set;public fun scroll(delta:ScrollDelta,source:ScrollSource,connection:NestedScrollConnection?=null):ScrollDelta{val pre=connection?.preScroll(delta,source)?:ScrollDelta(0f,0f);val local=delta-pre;val nx=(x+local.x).coerceIn(0f,maxX);val ny=(y+local.y).coerceIn(0f,maxY);val used=ScrollDelta(nx-x,ny-y);x=nx;y=ny;val remain=local-used;overscroll=remain;val post=connection?.postScroll(used,remain,source)?:ScrollDelta(0f,0f);return pre+used+post}}
public class VelocityTracker { private val samples=ArrayDeque<Pair<Long,Point>>();public fun add(time:Long,point:Point){samples+=time to point;while(samples.size>8)samples.removeFirst()};public fun velocity():ScrollDelta{if(samples.size<2)return ScrollDelta(0f,0f);val a=samples.first();val b=samples.last();val s=1_000_000_000f/(b.first-a.first).coerceAtLeast(1);return ScrollDelta((b.second.x-a.second.x)*s,(b.second.y-a.second.y)*s)} }
