package com.antepod.app

import com.antepod.lumentika.HeadlessFrameScheduler
import com.antepod.lumentika.PlatformServices
import com.antepod.lumentika.UiRoot
import com.antepod.lumentika.component.Component
import com.antepod.lumentika.component.UIComponent
import com.antepod.lumentika.components.*
import com.antepod.lumentika.geometry.Size
import com.antepod.lumentika.platform.UiEnvironment
import com.antepod.lumentika.reactive.derived
import com.antepod.lumentika.reactive.state
import com.antepod.lumentika.render.PaintArtifact
import com.antepod.lumentika.render.RenderBackend
import com.antepod.lumentika.runtime.Element
import com.antepod.lumentika.runtime.PaintCommand

@UIComponent
class ProofComponent : Component() {
    val title = prop("Generated by lumentika-ksp")
    val checked = binding(false)
    val change = event<Boolean>()
    val content = slot()
    lateinit var boundControl: ControlHandle
        private set

    override fun view(): Element = ui.column {
        text { title.value }
        boundControl = checkbox { bindValue(checked) }
        content.mount(this)
    }
}

data class ReactiveProof(
    val initialTexts: List<String>,
    val externalUpdateTexts: List<String>,
    val bindingWriteTexts: List<String>,
    val finalBindingValue: Boolean,
    val deliveredEvent: Boolean,
    val derivedExecutions: Int,
    val viewExecutions: Int,
    val componentDisposed: Boolean,
)

fun runReactiveProof(): ReactiveProof {
    val frames = HeadlessFrameScheduler()
    val artifacts = arrayOfNulls<PaintArtifact>(1)
    val root =
        UiRoot(
            UiEnvironment(Size(640f, 480f)),
            PlatformServices(frames),
            object : RenderBackend {
                override fun replay(artifact: PaintArtifact) {
                    artifacts[0] = artifact
                }
            },
        )
    val checked = state(false)
    val generatedTitle = state(7)
    var derivedExecutions = 0
    val doubledTitle = derived {
        derivedExecutions++
        generatedTitle.value * 2
    }
    val generatedValue = state(false)
    var generatedEvent: Boolean? = null
    lateinit var proof: ProofComponent
    root.scope.column {
        proofComponent {
            proof = component
            title { "Generated value: ${generatedTitle.value}" }
            bindChecked(generatedValue)
            onChange { generatedEvent = it }
            content { text { value = "Generated slot" } }
        }
        text { "Derived value: ${doubledTitle.value}" }
        text("Lumentika core")
        button {
            value = "Toggle"
            onClick { checked.value = !checked.value }
        }
        checkbox { bindValue(checked) }
        slider { value = 0.5f }
        textField {}
    }
    root.requestFrame()
    root.frame(1_000_000L)
    val initialTexts = artifacts.renderedTexts()
    check("Generated value: 7" in initialTexts)
    check("Derived value: 14" in initialTexts)
    check(doubledTitle.value == 14)
    check(derivedExecutions == 1)
    check("Generated slot" in initialTexts)
    check(!generatedValue.value)

    generatedTitle.value = 9
    generatedValue.value = true
    root.frame(2_000_000L)
    val externalUpdateTexts = artifacts.renderedTexts()
    check(proof.checked.value)
    check(proof.boundControl.semantics.checked == true)
    check("Generated value: 9" in externalUpdateTexts)
    check("Derived value: 18" in externalUpdateTexts)
    check(proof.viewExecutions == 1)

    proof.boundControl.activate()
    generatedTitle.value = 11
    root.frame(3_000_000L)
    val bindingWriteTexts = artifacts.renderedTexts()
    check(!generatedValue.value)
    check(proof.boundControl.semantics.checked == false)
    check("Generated value: 11" in bindingWriteTexts)
    check("Derived value: 22" in bindingWriteTexts)
    check(derivedExecutions == 3)
    check(proof.viewExecutions == 1)

    proof.change.emit(false)
    check(generatedEvent == false)
    root.close()

    proof.change.emit(true)
    proof.checked.value = true
    check(generatedEvent == false)
    check(!generatedValue.value)
    check(proof.componentScope.isDisposed)

    return ReactiveProof(
        initialTexts,
        externalUpdateTexts,
        bindingWriteTexts,
        generatedValue.value,
        requireNotNull(generatedEvent),
        derivedExecutions,
        proof.viewExecutions,
        proof.componentScope.isDisposed,
    )
}

fun main() {
    val proof = runReactiveProof()
    println(
        "Lumentika reactive proof passed: value=${proof.finalBindingValue}, " +
            "event=${proof.deliveredEvent}, derivedExecutions=${proof.derivedExecutions}, " +
            "viewExecutions=${proof.viewExecutions}"
    )
}

private fun Array<PaintArtifact?>.renderedTexts(): List<String> =
    requireNotNull(this[0])
        .chunks
        .flatMap { it.commands }
        .filterIsInstance<PaintCommand.DrawText>()
        .map(PaintCommand.DrawText::text)
